name: Cypress Tests

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false

      - name: Save build folder
        uses: actions/upload-artifact@v2


  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4